# -*- coding: utf-8 -*-
"""Examen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N7vsGGObd5b2F5KcyARoXA2tCp8HQ89F
"""

def raices(a,b,c): 
 print("la Solucion a una raiz cubica ax^2 + bx + c")
 x1 = (-b + ((b**2) - (4*a*c))**0.5) /(2*a)
 x2 = (-b - ((b**2) - (4*a*c))**0.5) / (2*a)

 print("x1 = ",x1)
 print("x2 = ",x2)
 
a = float (input("Ingrese el valor de a"))
b = float (input("Ingrese el valor de b"))
c = float (input("Ingrese el valor de c"))

while ((b**2) - (4*a*c)) < 0:
  print(" Error, el discriminante tiene que ser positivo")
  a = float (input("Ingrese el valor de a"))
  b = float (input("Ingrese el valor de b"))
  c = float (input("Ingrese el valor de c"))

raices(a,b,c)

def euler(x,e = 2.7182818282):
  print("La funcion = e^-x")
  print("Cuando e =",e1)
  
e1 = 2.7182818282**-x 
 
x = int (input("Ingrese el valor de x"))
euler(e1)

A=[]
 
i=-4
p=10
while i< p:    
  z=i
  x=-4
  while z==3 and x<7:   
 
    w=euler(x)
    print(w)
    x=x+1 
    A.append(w)
  i=i+1  
 
print(A)